---
radiopad_players:
  hosts:
    # Registry data: https://github.com/briceburg/radio-pad-registry-data/pull/1
    radio-canones:
      ansible_host: radio-canones.lan
      radiopad_player: briceburg/canones
      radiopad_audio_device: alsa/default:CARD=DAC
      radiopad_timezone: America/Denver
