services:
  player:
    build:
      context: ./player
    environment:
      PULSE_SERVER: "unix:/run/user/${UID:-1000}/pulse/native"
      RADIOPAD_SWITCHBOARD_URL: "ws://switchboard:1980/"
    tty: true
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./player:/app
      - /run/user/${UID:-1000}/pulse:/run/user/${UID:-1000}/pulse

  switchboard:
    build:
      context: ./switchboard
    ports:
      - "1980:1980"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./switchboard:/app

  remote-control:
    build:
      context: ./remote-control
    environment:
      VITE_SWITCHBOARD_URL: "ws://switchboard:1980/"
    ports:
      - "5173:5173"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./remote-control:/app
