services:
  registry:
    extends:
      file: compose.yaml
      service: registry
    environment:
      REGISTRY_PROFILES: "api"

  switchboard:
    extends:
      file: compose.yaml
      service: registry
    ports:
      - "${RADIOPAD_SWITCHBOARD_PORT}:1980"
    environment:
      REGISTRY_PROFILES: "switchboard"
      REGISTRY_BIND_PORT: "1980"
      REGISTRY_URL: "http://registry:1980/api/"

  player:
    extends:
      file: compose.yaml
      service: player
    environment:
      RADIOPAD_REGISTRY_URL: "http://registry:1980/api/"
      RADIOPAD_SWITCHBOARD_URL: "ws://switchboard:1980/switchboard/briceburg/living-room"

  remote-control:
    extends:
      file: compose.yaml
      service: remote-control
    environment:
      VITE_REGISTRY_URL: "/api/"
      VITE_SWITCHBOARD_URL: "/switchboard"
      RADIOPAD_REGISTRY_PROXY_TARGET: "http://registry:1980"
      RADIOPAD_SWITCHBOARD_PROXY_TARGET: "ws://switchboard:1980"

  integration-tests:
    extends:
      file: compose.yaml
      service: integration-tests
    depends_on:
      switchboard:
        condition: service_healthy
    environment:
      REGISTRY_URL: "http://registry:1980/api"
      SWITCHBOARD_URL: "ws://switchboard:1980/switchboard"
