services:
  registry:
    build:
      context: ./registry
      target: dev
    ports:
      - "${RADIOPAD_REGISTRY_PORT}:1980"
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      REGISTRY_PROFILES: "api,switchboard"
      REGISTRY_BIND_PORT: "1980"
    volumes:
      - ./registry:/app

  player:
    build:
      context: ./player
      target: dev
    depends_on:
      registry:
        condition: service_healthy
    environment:
      RADIOPAD_REGISTRY_URL: "http://registry:1980/api/"
      RADIOPAD_PLAYER: "briceburg/living-room"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./player:/app

  remote-control:
    build:
      context: ./remote-control
      target: dev
    environment:
      VITE_REGISTRY_URL: "http://registry:1980/api/"
      VITE_SWITCHBOARD_URL: "ws://registry:1980/switchboard/"
    ports:
      - "${RADIOPAD_REMOTE_CONTROL_PORT}:5173"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./remote-control:/app

  integration-tests:
    profiles:
      - tests
    build:
      context: ./tests/integration
    depends_on:
      player:
        condition: service_healthy
      remote-control:
        condition: service_healthy
    environment:
      REGISTRY_URL: "http://registry:1980/api"
      SWITCHBOARD_URL: "ws://registry:1980/switchboard"
      REMOTE_CONTROL_URL: "http://remote-control:5173"
