name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - macropad-control
          - player
          - switchboard
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache-dependency-path: ./${{ matrix.project }}/requirements-dev.txt
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run CI
        run: bin/ci

  node-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - remote-control
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache-dependency-path: ./${{ matrix.project }}/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run CI
        run: bin/ci
